version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "9000:9000"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:8.3-fpm
    container_name: php-container
    volumes:
      - ./html:/var/www/html
    environment:
      - PHP_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

